name: CI

on:
  # run it on push to the default repository branch
  push:
    branches: [main]
    paths-ignore:
      - '.github/**'

  # run it during pull request
  pull_request:
    paths-ignore:
      - '.github/**'

jobs:
  build:

    name: CI

    # run only when code is compiling and tests are passing
    runs-on: ubuntu-latest

    steps:

      # Check out our code
      - name: Checkout code
        uses: actions/checkout@v2

      # setup Docker build action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: false

          # TODO: Add checking
          #cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/simplewhale:buildcache
          #cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/simplewhale:buildcache,mode=max

